# all
UAV_ID: 1 
# formation_cbf.launch
group_name: "MAV1"
# formation_node.cpp

laplacian: [true,   false,  false,  false,  false,
            true,   true,  false,  false,  false,
            true,   true,  true,  false,  false,
            true,   true,  false,  true,  false,
            false,   true,  false,  false,  true]

# velocity_cbf_generator_node.cpp

D: 0.3 # safety distance
gamma: 0.5 # CBF constraint param

# topic_tools.cpp

sub_topic: "/vrpn_client_node/MAV1/pose"